# Generated by Django 3.0.10 on 2020-10-18 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('s_type', models.IntegerField(blank=True, choices=[(1, 'Highly accessible school'), (2, 'Accessible Schools'), (5, 'Highly Inaccessible Schools'), (4, 'Inaccessible Schools')])),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applicant.District')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=50)),
                ('aadhaar', models.CharField(max_length=50)),
                ('chronic_disease', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=30)),
                ('child_disease', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=30)),
                ('disabled', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=30)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=30)),
                ('dob', models.DateField(verbose_name='dob')),
                ('age', models.CharField(blank=True, max_length=15, null=True, verbose_name='age')),
                ('marital_status', models.CharField(choices=[('married', 'MARRIED'), ('unmarried', 'SINGLE')], default='single', max_length=30)),
                ('join_date', models.DateField(verbose_name='join_date')),
                ('experience', models.IntegerField(verbose_name='experience')),
                ('au_points', models.IntegerField(blank=True, null=True, verbose_name='points')),
                ('direct_eligible', models.BooleanField(default=False)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applicant.District')),
                ('email', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='applicant_email', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applicant_school', to='applicant.School')),
            ],
        ),
    ]
