# Generated by Django 3.0.10 on 2020-10-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantuser',
            name='aadhaar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applicantuser',
            name='child_disease',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='applicantuser',
            name='chronic_disease',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='applicantuser',
            name='direct_eligible',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='applicantuser',
            name='disabled',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='applicantuser',
            name='dob',
            field=models.DateField(null=True, verbose_name='dob'),
        ),
        migrations.AlterField(
            model_name='applicantuser',
            name='experience',
            field=models.IntegerField(null=True, verbose_name='experience'),
        ),
        migrations.AlterField(
            model_name='applicantuser',
            name='gender',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='applicantuser',
            name='join_date',
            field=models.DateField(null=True, verbose_name='join_date'),
        ),
        migrations.AlterField(
            model_name='applicantuser',
            name='marital_status',
            field=models.CharField(choices=[('married', 'MARRIED'), ('unmarried', 'SINGLE')], default='single', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='applicantuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
