# Generated by Django 3.0.10 on 2020-10-18 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0003_auto_20201018_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantuser',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applicant_school', to='applicant.School'),
        ),
    ]
